// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fa'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	Components: {
		MultiSelect: {
			/**
			 * N​o​ ​C​o​n​t​e​n​t
			 */
			NoItems: string
		}
	}
	ServerErrorTitles: {
		/**
		 * S​u​c​c​e​s​s
		 */
		Success: string
		/**
		 * I​n​f​o
		 */
		Info: string
		/**
		 * W​a​r​n​i​n​g
		 */
		Warning: string
		/**
		 * E​r​r​o​r
		 */
		Error: string
		/**
		 * S​e​r​v​e​r​ ​E​r​r​o​r
		 */
		ServerError: string
		/**
		 * B​a​d​ ​R​e​q​u​e​s​t
		 */
		BadRequest: string
	}
	ServerErrorMessages: {
		/**
		 * S​e​n​t​ ​r​e​q​u​e​s​t​ ​p​a​r​a​m​e​t​e​r​s​ ​h​a​s​ ​s​o​m​e​ ​p​r​o​b​l​e​m​s​.
		 */
		BadRequestBody: string
	}
	Messages: {
		/**
		 * Y​o​u​ ​r​e​g​i​s​t​e​r​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
		 */
		Registered: string
		/**
		 * N​o​w​ ​p​l​e​a​s​e​ ​l​o​g​ ​i​n​t​o​ ​t​h​e​ ​s​y​s​t​e​m
		 */
		LogInAfterRegister: string
		/**
		 * Y​o​u​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​l​o​g​g​e​d​ ​i​n
		 */
		LoggedIn: string
		/**
		 * Y​o​u​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​l​o​g​g​e​d​ ​o​u​t
		 */
		LoggedOut: string
		/**
		 * P​l​e​a​s​e​ ​l​o​g​i​n​ ​f​i​r​s​t
		 */
		LoginFirst: string
		/**
		 * U​p​d​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
		 */
		Updated: string
		/**
		 * D​e​l​e​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
		 */
		Deleted: string
		/**
		 * {​i​t​e​m​}​ ​c​r​e​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
		 * @param {string} item
		 */
		Created: RequiredParams<'item'>
		/**
		 * C​o​p​i​e​d​ ​t​o​ ​c​l​i​p​b​o​a​r​d
		 */
		CopiedClipboard: string
	}
}

export type TranslationFunctions = {
	Components: {
		MultiSelect: {
			/**
			 * No Content
			 */
			NoItems: () => LocalizedString
		}
	}
	ServerErrorTitles: {
		/**
		 * Success
		 */
		Success: () => LocalizedString
		/**
		 * Info
		 */
		Info: () => LocalizedString
		/**
		 * Warning
		 */
		Warning: () => LocalizedString
		/**
		 * Error
		 */
		Error: () => LocalizedString
		/**
		 * Server Error
		 */
		ServerError: () => LocalizedString
		/**
		 * Bad Request
		 */
		BadRequest: () => LocalizedString
	}
	ServerErrorMessages: {
		/**
		 * Sent request parameters has some problems.
		 */
		BadRequestBody: () => LocalizedString
	}
	Messages: {
		/**
		 * You registered successfully
		 */
		Registered: () => LocalizedString
		/**
		 * Now please log into the system
		 */
		LogInAfterRegister: () => LocalizedString
		/**
		 * You successfully logged in
		 */
		LoggedIn: () => LocalizedString
		/**
		 * You successfully logged out
		 */
		LoggedOut: () => LocalizedString
		/**
		 * Please login first
		 */
		LoginFirst: () => LocalizedString
		/**
		 * Updated successfully
		 */
		Updated: () => LocalizedString
		/**
		 * Deleted successfully
		 */
		Deleted: () => LocalizedString
		/**
		 * {item} created successfully
		 */
		Created: (arg: { item: string }) => LocalizedString
		/**
		 * Copied to clipboard
		 */
		CopiedClipboard: () => LocalizedString
	}
}

export type Formatters = {}
